// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using casaDeShows.Data;

namespace casaDeShows.Migrations.ApplicationDbContextEntidadesMigrations
{
    [DbContext(typeof(ApplicationDbContextEntidades))]
    [Migration("20200217180039_CriandoEntidadesEvento")]
    partial class CriandoEntidadesEvento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("casaDeShows.Models.CasaDeShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NomeCasaDeShow")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("CasaDeShows");
                });

            modelBuilder.Entity("casaDeShows.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCasaDeShowsId")
                        .HasColumnType("int");

                    b.Property<int?>("IdGeneroDoEventoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeDoEvento")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("PrecoIngresso")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdCasaDeShowsId");

                    b.HasIndex("IdGeneroDoEventoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("casaDeShows.Models.GeneroEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("GeneroEventos");
                });

            modelBuilder.Entity("casaDeShows.Models.Evento", b =>
                {
                    b.HasOne("casaDeShows.Models.CasaDeShow", "IdCasaDeShows")
                        .WithMany()
                        .HasForeignKey("IdCasaDeShowsId");

                    b.HasOne("casaDeShows.Models.GeneroEvento", "IdGeneroDoEvento")
                        .WithMany()
                        .HasForeignKey("IdGeneroDoEventoId");
                });
#pragma warning restore 612, 618
        }
    }
}
